### ISSUE TITLE
[Other issue]: Waypoints labels are not properly align with waypoint.

### ISSUE THREAD

**Issue by harshp1509** [open-rmf/rmf-web#1034]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I am trying to visualize the world environment than waypoint label are not align with the waypoints. so what parameters i have to change to align it?
![Screenshot 2024-11-25 101601](https://github.com/user-attachments/assets/4ad3e374-402d-474b-a8e2-1b1c9d68c429)

**Comment by harshp1509** [comment]
I am using humble branch of rmf_web.
I have tried with two maps one is gazebo_world and another is my own custom created map. for both map, i am facing same issue.

This both map's building.yaml and image :-

gazebo world map:-

```
coordinate_system: reference_image
crowd_sim:
  agent_groups:
    - {agents_name: [], agents_number: 0, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.40000000000000002, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: turtlebot_world_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.10000000000000001
graphs:
  {}
levels:
  turtlebot_world:
    drawing:
      filename: world.png
    elevation: 0
    lanes:
      - [0, 1, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [1, 2, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [2, 3, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [3, 4, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [4, 5, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [5, 6, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [6, 7, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [7, 0, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [8, 9, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [9, 5, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [5, 2, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [2, 10, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [10, 11, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [11, 1, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [1, 6, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [6, 18, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [18, 8, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
    layers:
      {}
    measurements:
      - [12, 13, {distance: [3, 5.2976000000000001]}]
      - [14, 15, {distance: [3, 5.0914999999999999]}]
    models:
      - {dispensable: false, model_name: OpenRobotics/TeleportDispenser, name: coke_dispenser, static: true, x: 214.422, y: 172.90100000000001, yaw: 1.5708, z: 0}
      - {dispensable: false, model_name: OpenRobotics/TeleportIngestor, name: coke_ingestor, static: true, x: 215.459, y: 223.16900000000001, yaw: 2.8668, z: 0}
      - {dispensable: false, model_name: OpenRobotics/Coke, name: OpenRobotics/Coke, static: false, x: 212.608, y: 172.81399999999999, yaw: 1.5708, z: 0}
    vertices:
      - [163.607, 170.38999999999999, 0, goal0]
      - [190.62899999999999, 172.179, 0, goal1, {is_parking_spot: [4, true]}]
      - [213.714, 173.07400000000001, 0, pantry, {is_holding_point: [4, true], pickup_dispenser: [1, coke_dispenser]}]
      - [234.47300000000001, 172.71600000000001, 0, goal3]
      - [234.83099999999999, 194.54900000000001, 0, goal4, {dropoff_ingestor: [1, coke]}]
      - [211.03, 194.90700000000001, 0, goal5]
      - [189.018, 193.654, 0, goal6]
      - [163.785, 195.80199999999999, 0, tb3_0_start, {is_charger: [4, true], is_parking_spot: [4, true]}]
      - [189.73400000000001, 221.392, 0, goal7_1, {dock_name: [1, goal7_1], is_cleaning_zone: [4, true]}]
      - [215.14599999999999, 222.82400000000001, 0, hardware_2, {dropoff_ingestor: [1, coke_ingestor], is_holding_point: [4, true]}]
      - [213.536, 146.946, 0, goal10]
      - [189.197, 145.87299999999999, 0, goal9]
      - [142.27099999999999, 183.25200000000001, 0, ""]
      - [248.21299999999999, 184.684, 0, ""]
      - [202.042, 132.965, 0, ""]
      - [202.93700000000001, 234.792, 0, ""]
      - [174.697, 218.196, 0, step_2]
      - [182.30699999999999, 213.71299999999999, 0, step_1]
      - [189.11500000000001, 208.74600000000001, 0, goal7_1_start]
      - [182.203, 223.304, 0, step_3]
      - [166.001, 143.60900000000001, 0, ""]
      - [173.41, 142.95599999999999, 0, ""]
      - [179.07599999999999, 133.58500000000001, 0, ""]
      - [223.31399999999999, 133.36699999999999, 0, ""]
      - [228.32599999999999, 143.173, 0, ""]
      - [237.25999999999999, 144.69900000000001, 0, ""]
      - [252.95099999999999, 174.77199999999999, 0, ""]
      - [253.16900000000001, 194.38499999999999, 0, ""]
      - [236.82499999999999, 224.02199999999999, 0, ""]
      - [227.88999999999999, 224.67599999999999, 0, ""]
      - [222.22399999999999, 234.91800000000001, 0, ""]
      - [178.63999999999999, 234.91800000000001, 0, ""]
      - [172.756, 223.804, 0, ""]
      - [163.60300000000001, 223.15000000000001, 0, ""]
    walls:
      - [20, 21, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [21, 22, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [22, 23, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [23, 24, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [24, 25, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [25, 26, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [26, 13, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [13, 27, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [27, 28, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [28, 29, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [29, 30, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [30, 31, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [31, 32, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [32, 33, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [33, 12, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [12, 20, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
lifts: {}
name: world
```
![world](https://github.com/user-attachments/assets/5bd9be5a-2f59-4362-a2ec-30d3f738205b)


this is my custom map:-


```
coordinate_system: reference_image
crowd_sim:
  agent_groups:
    - {agents_name: [], agents_number: 0, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.40000000000000002, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: turtlebot_world_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.10000000000000001
graphs:
  {}
levels:
  turtlebot_world:
    drawing:
      filename: demo_map.png
    elevation: 0
    floors:
      - parameters: {ceiling_scale: [3, 1], ceiling_texture: [1, blue_linoleum], indoor: [2, 0], texture_name: [1, blue_linoleum], texture_rotation: [3, 0], texture_scale: [3, 1]}
        vertices: [0, 1, 2, 3, 4, 5, 6]
    lanes:
      - [15, 16, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [16, 17, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [22, 23, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [23, 24, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [24, 25, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [18, 19, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [19, 20, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [20, 21, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [17, 26, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [26, 22, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [26, 18, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
    layers:
      {}
    measurements:
      - [11, 12, {distance: [3, 3.1400999999999999]}]
      - [13, 14, {distance: [3, 2.1318000000000001]}]
    vertices:
      - [30.454000000000001, 50.060000000000002, 0, ""]
      - [59.813000000000002, 50.314999999999998, 0, ""]
      - [91.852000000000004, 50.186999999999998, 0, ""]
      - [92.361999999999995, 91.162000000000006, 0, ""]
      - [73.471000000000004, 91.034000000000006, 0, ""]
      - [30.326000000000001, 90.522999999999996, 0, ""]
      - [30.071000000000002, 76.992999999999995, 0, ""]
      - [59.813000000000002, 69.078999999999994, 0, ""]
      - [49.856000000000002, 69.206000000000003, 0, ""]
      - [73.980999999999995, 74.822999999999993, 0, ""]
      - [40.283000000000001, 76.864999999999995, 0, ""]
      - [92.489999999999995, 44.060000000000002, 0, ""]
      - [29.687999999999999, 43.933, 0, ""]
      - [100.276, 49.037999999999997, 0, ""]
      - [100.65900000000001, 91.671999999999997, 0, ""]
      - [37.271999999999998, 83.224999999999994, 0, charging_point, {is_charger: [4, true], is_parking_spot: [4, true]}]
      - [55.652999999999999, 83.480000000000004, 0, waypoint_1]
      - [68.849000000000004, 84.269000000000005, 0, waypoint_2]
      - [47.738999999999997, 74.034000000000006, 0, waypoint_3]
      - [39.908999999999999, 66.670000000000002, 0, waypoint_4]
      - [44.579000000000001, 58.247, 0, waypoint_5]
      - [54.670999999999999, 59.914999999999999, 0, office, {is_cleaning_zone: [4, true]}]
      - [69.694000000000003, 63.695, 0, packaging]
      - [79.650999999999996, 62.036000000000001, 0, waypoint_6]
      - [83.863, 70.204999999999998, 0, waypoint_7]
      - [83.224999999999994, 82.203999999999994, 0, shipping]
      - [67.787999999999997, 74.599000000000004, 0, packpath]
    walls:
      - [0, 1, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [1, 2, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [2, 3, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [3, 4, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [4, 5, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [5, 6, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [6, 0, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [1, 7, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [7, 8, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [4, 9, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [6, 10, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
lifts: {}
name: demo
```
![demo_map](https://github.com/user-attachments/assets/2fbb0ff1-928c-4b00-9ec1-2c38b21c755e)
